---
title:               Kacy Fortner
tagline:             Southern gentleman. Electronic music enthusiast. Progressive Metal dude. Wannabe rockstar. Formerly at UNC. Hacker at Adzerk.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Kacy Fortner
twitter:             kacyf
github:              kacy 
email:               kacy@kacyfortner.com
google_analytics_id: UA-9625728-1 